# Python package
# Clone the repository for mandatory injected checks

trigger:
- main
pool:
  vmImage: ubuntu-latest
variables:
  Codeql.Enabled: true
strategy:
  matrix:
    Python310-onnx:
      python.version: '3.10'
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'
