# Build the release version of the package and publish to artifacts

# To configure triggers, see https://github.com/microsoft/onnx-converters-private/wiki/ONNX-Script-release
trigger: none

pool:
  vmImage: ubuntu-latest
variables:
  CI: 'true'
  # Set the release environment variable to build a release version of the wheel
  ONNX_SCRIPT_RELEASE: 1
steps:
  - template: _release-template.yml
